spring.application.name=componente-2
spring.datasource.url=jdbc:mysql://localhost:3306/school_
api?createDatabaseIfNotExist=true&useSSL=false&allowPubli
cKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=goncas0808

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

