spring.application.name = Equipa9_Comp2
spring.datasource.url = jdbc:mysql://localhost:3306/equipa9_db
spring.datasource.driverClassName = com.mysql.cj.jdbc.Driver
spring.datasource.username = root
spring.datasource.password = Mysql123#
spring.jpa.database-platform = org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto = update

